%PREX_CLASSIFIERS, includes combiners
%
% Test all classifier defaults

combc = qdc([],[],1e-6);
classf = {knnc([],1),knnc,statsknnc,parzenc,parzendc,...
          nmc,nmc*combc,nmsc,nmsc*combc, ...
          fisherc,fisherc*combc,quadrc, ...
          ldc,statslinc,klldc,pcldc, ...
          udc,qdc,mogc,...
          loglc,loglc*combc,logmlc, ...
          treec,dtc,statsdtc,randomforestc ...
          svc,svc*combc,nusvc,nusvc*combc, ...
          libsvc,nulibsvc, ...
          pksvc,rbsvc,rblibsvc,pklibsvc, ...
          statssvc,statssvc*combc,pkstatssvc,rbstatssvc, ...
          perlc,perlc*combc,lmnc,bpxnc,rnnc,neurc,rbnc, ...
          fdsc,adaboostc,rfishercc, ...
          lkc,lkc*combc, ...
          rsscc,rsscc*combc,baggingc,baggingc*combc, ...
          naivebc,statsnbc, ...
          drbmc,vpc,vpc*combc, ...
          subsc,subsc*combc, ...
          weakc,weakc*combc, ...
          };
gridsize(100);
randreset;
trainsize = 250;
t = gendatm(1000);
a = gendatm(trainsize);
a
delfigs
w = cell(1,numel(classf));
e = zeros(1,numel(classf));
t0 = zeros(1,numel(classf));
t1 = zeros(1,numel(classf));
for j=1:numel(classf)
  tic; w{j} = a*classf{j};  t0(j) = toc;
  tic; e(j) = t*w{j}*testc; t1(j) = toc;
  figure(j)
  scatterd(a);
  title(getname(classf{j}));
  fprintf('%2i %20s %7.3f  %7.3f  %7.3f\n',j,getname(classf{j}),e(j),t0(j), t1(j));
  plotc(w{j})
  drawnow
end
showfigs
names = char(getname(classf));
[ss,L] = sort(e);
for i=1:max(L)
  fprintf(' %3i  %20s  %6.3f\n',i,names(L(i),:),e(L(i)));
end
