%PREX_CLASSIFIERS_SMALL: some classes have no, a just one object
%
% Test all classifier defaults

classf = {knnc([],1),knnc,parzenc,parzendc,udc,qdc,mogc,...
          klldc,pcldc,treec,randomforestc,dtc, ...
          pksvc,rbsvc,rblibsvc,pklibsvc,loglc,neurc,bpxnc, ...
          lmnc,rbnc,rnnc,fdsc,naivebc,adaboostc, ...
          drbmc,rfishercc, ...
          statsdtc,statsknnc,statslinc,statsnbc,statssvc,pkstatssvc,rbstatssvc, ...
          nmc, ...
          nmsc, ...
          fisherc, ...
          ldc, ...
          quadrc, ...
          svc, ...
          nusvc, ...
          libsvc, ...
          nulibsvc, ...
          subsc, ...
          perlc, ...
          vpc, ...
          weakc, ...
          lkc, ...
          rsscc, ...
          baggingc, ...
          };
%           nmc*fishercc, ...
%           nmsc*fishercc, ...
%           fisherc*fishercc, ...
%           ldc*fishercc, ...
%           quadrc*fishercc, ...
%           svc*fishercc, ...
%           nusvc*fishercc, ...
%           libsvc*fishercc, ...
%           nulibsvc*fishercc, ...
%           subsc*fishercc, ...
%           perlc*fishercc, ...
%           vpc*fishercc, ...
%           weakc*fishercc, ...
%           lkc*fishercc, ...
%           rsscc*fishercc, ...
%           baggingc*fishercc, ...
%           };
gridsize(100);
randreset;
trainsize = [3 0 5 0 1 5 0 1];
dimension = 4;
t = genmdat('gendatm',dimension,1000);
a = genmdat('gendatm',dimension,trainsize);
w = cmapm(dimension,'randrot');
a = a*w;
t = t*w;
a
delfigs
w = cell(1,numel(classf));
% v = cell(1,numel(classf));
% u = cell(1,numel(classf));
e = zeros(1,numel(classf));
% f = zeros(1,numel(classf));
% g = zeros(1,numel(classf));
t0 = zeros(1,numel(classf));
t1 = zeros(1,numel(classf));
for j=1:numel(classf)
  tic; w{j} = a*classf{j};  t0(j) = toc;
  tic; e(j) = t*w{j}*testc; t1(j) = toc;
%   v{j} = a*(w{j}*fishercc);
%   u{j} = a*(w{j}*fisherc);
%   f(j) = t*v{j}*testc;
%   g(j) = t*u{j}*testc;
%   figure(j)
%   scatterd(a);
%   title(getname(classf{j}));
%     fprintf('%2i %20s %7.3f  %7.3f  %7.3f  %7.3f  %7.3f\n',j,getname(classf{j}),e(j),f(j),g(j),t0(j), t1(j));
    fprintf('%2i %20s %7.3f  %7.3f  %7.3f\n',j,getname(classf{j}),e(j),t0(j), t1(j));
%   plotc(w{j})
%   drawnow
end
% save gendatm250 e f g t0 t1 w classf
% showfigs;
% s0 = prdataset([e' t0']);
% s0 = setident(s0,getname(classf)');
% s1 = prdataset([e' t1']);
% s1 = setident(s1,getname(classf)');
% figure; scattern(log(s0),[],'idents'); axis square; fontsize(8);
% figure; scattern(log(s1),[],'idents'); axis square; fontsize(8);
% figsave('gendatm250',[]);

names = char(getname(classf));
[ss,L] = sort(e);
for i=1:max(L)
  fprintf(' %3i  %20s  %6.3f\n',i,names(L(i),:),e(L(i)));
end
save exp2 trainsize names e
